main: main.o CListarClases.o CEliminarAsignatura.o DtParticipacion.o DtIniciarMonitoreo.o DtIniciarClaseFull.o DtIniciarClase.o ControladorInicioClase.o CEnvioMensaje.o DtInstanciaClase.o CInscripcionAAsignaturas.o DtAsignatura.o DtEstudiante.o DtDocente.o Asignatura.o AsisteEnVivo.o Clase.o CAsignacionDocente.o ControladorAltaAsignatura.o ControladorAltaUsuario.o Docente.o DtFecha.o DtLog.o DtPerfil.o DtTimeStamp.o Estudiante.o Fabrica.o Monitoreo.o Participacion.o Perfil.o Practico.o Rol.o Teorico.o ManejadorAsignatura.o ManejadorClase.o ManejadorPerfil.o
	g++ main.o CListarClases.o CEliminarAsignatura.o DtParticipacion.o DtIniciarMonitoreo.o DtIniciarClaseFull.o DtIniciarClase.o ControladorInicioClase.o CEnvioMensaje.o DtInstanciaClase.o CInscripcionAAsignaturas.o DtAsignatura.o DtEstudiante.o DtDocente.o Asignatura.o AsisteEnVivo.o Clase.o CAsignacionDocente.o ControladorAltaAsignatura.o ControladorAltaUsuario.o Docente.o DtFecha.o DtLog.o DtPerfil.o DtTimeStamp.o Estudiante.o Fabrica.o Monitoreo.o Participacion.o Perfil.o Practico.o Rol.o Teorico.o ManejadorAsignatura.o ManejadorClase.o ManejadorPerfil.o -g -o sistema

CListarClases.o :CListarClases.cpp
	g++ -g -c CListarClases.cpp

CEliminarAsignatura.o : CEliminarAsignatura.cpp
	g++ -g -c CEliminarAsignatura.cpp

DtParticipacion.o : DtParticipacion.cpp
	g++ -g -c DtParticipacion.cpp

DtIniciarMonitoreo.o : DtIniciarMonitoreo.cpp
	g++ -g -c DtIniciarMonitoreo.cpp

DtIniciarClaseFull.o : DtIniciarClaseFull.cpp
	g++ -g -c DtIniciarClaseFull.cpp

DtIniciarClase.o : DtIniciarClase.cpp
	g++ -g -c DtIniciarClase.cpp

ControladorInicioClase.o : ControladorInicioClase.cpp
	g++ -g -c ControladorInicioClase.cpp

CEnvioMensaje.o : CEnvioMensaje.cpp
	g++ -g -c CEnvioMensaje.cpp

CInscripcionAAsignaturas.o : CInscripcionAAsignaturas.cpp
	g++ -g -c CInscripcionAAsignaturas.cpp

main.o : main.cpp
	g++ -g -c  main.cpp

CAsignacionDocente.o : CAsignacionDocente.cpp
	g++ -g -c CAsignacionDocente.cpp
	
ControladorAltaAsignatura.o : ControladorAltaAsignatura.cpp
	g++ -g -c ControladorAltaAsignatura.cpp
	
DtInstanciaClase.o : DtInstanciaClase.cpp
	g++ -g -c DtInstanciaClase.cpp

DtAsignatura.o : DtAsignatura.cpp
	g++ -g -c DtAsignatura.cpp

Asignatura.o : Asignatura.cpp
	g++ -g -c Asignatura.cpp

AsisteEnVivo.o : AsisteEnVivo.cpp
	g++ -g -c AsisteEnVivo.cpp

Clase.o : Clase.cpp
	g++ -g -c Clase.cpp

ControladorAltaUsuario.o : ControladorAltaUsuario.cpp
	g++ -g -c ControladorAltaUsuario.cpp

Docente.o : Docente.cpp
	g++ -g -c Docente.cpp

DtFecha.o : DtFecha.cpp
	g++ -g -c DtFecha.cpp

DtLog.o : DtLog.cpp
	g++ -g -c DtLog.cpp

DtPerfil.o : DtPerfil.cpp
	g++ -g -c DtPerfil.cpp

DtTimeStamp.o : DtTimeStamp.cpp
	g++ -g -c DtTimeStamp.cpp

Estudiante.o : Estudiante.cpp
	g++ -g -c Estudiante.cpp

Fabrica.o : Fabrica.cpp
	g++ -g -c Fabrica.cpp

Monitoreo.o : Monitoreo.cpp
	g++ -g -c Monitoreo.cpp

Participacion.o : Participacion.cpp
	g++ -g -c Participacion.cpp

Perfil.o : Perfil.cpp
	g++ -g -c Perfil.cpp

Practico.o : Practico.cpp
	g++ -g -c Practico.cpp

Rol.o : Rol.cpp
	g++ -g -c Rol.cpp

Teorico.o : Teorico.cpp
	g++ -g -c Teorico.cpp

ManejadorAsignatura.o : ManejadorAsignatura.cpp
	g++ -g -c ManejadorAsignatura.cpp

ManejadorClase.o : ManejadorClase.cpp
	g++ -g -c ManejadorClase.cpp

ManejadorPerfil.o : ManejadorPerfil.cpp
	g++ -g -c ManejadorPerfil.cpp

DtDocente.o : DtDocente.cpp
	g++ -g -c DtDocente.cpp

DtEstudiante.o : DtEstudiante.cpp
	g++ -g -c DtEstudiante.cpp

clean:
	rm -rf *.o sistema
	clear